package com.ssdy.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.ssdy.Bean.Site;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SITE".
*/
public class SiteDao extends AbstractDao<Site, Long> {

    public static final String TABLENAME = "SITE";

    /**
     * Properties of entity Site.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OwnerId = new Property(1, long.class, "ownerId", false, "OWNER_ID");
    }

    private Query<Site> user_OwnedSitesQuery;

    public SiteDao(DaoConfig config) {
        super(config);
    }
    
    public SiteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SITE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"OWNER_ID\" INTEGER NOT NULL );"); // 1: ownerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SITE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Site entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getOwnerId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Site entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getOwnerId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Site readEntity(Cursor cursor, int offset) {
        Site entity = new Site( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1) // ownerId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Site entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOwnerId(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Site entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Site entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Site entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "ownedSites" to-many relationship of User. */
    public List<Site> _queryUser_OwnedSites(long ownerId) {
        synchronized (this) {
            if (user_OwnedSitesQuery == null) {
                QueryBuilder<Site> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OwnerId.eq(null));
                user_OwnedSitesQuery = queryBuilder.build();
            }
        }
        Query<Site> query = user_OwnedSitesQuery.forCurrentThread();
        query.setParameter(0, ownerId);
        return query.list();
    }

}
