package com.example.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.bean.information;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "INFORMATION".
*/
public class informationDao extends AbstractDao<information, Long> {

    public static final String TABLENAME = "INFORMATION";

    /**
     * Properties of entity information.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Address = new Property(1, String.class, "address", false, "ADDRESS");
        public final static Property Icon_url = new Property(2, String.class, "icon_url", false, "ICON_URL");
        public final static Property Score = new Property(3, int.class, "score", false, "SCORE");
    }


    public informationDao(DaoConfig config) {
        super(config);
    }
    
    public informationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"INFORMATION\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ADDRESS\" TEXT NOT NULL ," + // 1: address
                "\"ICON_URL\" TEXT NOT NULL ," + // 2: icon_url
                "\"SCORE\" INTEGER NOT NULL );"); // 3: score
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"INFORMATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, information entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAddress());
        stmt.bindString(3, entity.getIcon_url());
        stmt.bindLong(4, entity.getScore());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, information entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAddress());
        stmt.bindString(3, entity.getIcon_url());
        stmt.bindLong(4, entity.getScore());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public information readEntity(Cursor cursor, int offset) {
        information entity = new information( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // address
            cursor.getString(offset + 2), // icon_url
            cursor.getInt(offset + 3) // score
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, information entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAddress(cursor.getString(offset + 1));
        entity.setIcon_url(cursor.getString(offset + 2));
        entity.setScore(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(information entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(information entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(information entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
