package com.example.bean;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "INFORMATION".
 */
@Entity
public class information implements java.io.Serializable {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String address;

    @NotNull
    private String icon_url;
    private int score;

    @Generated(hash = 745866116)
    public information() {
    }

    public information(Long id) {
        this.id = id;
    }

    @Generated(hash = 1120984582)
    public information(Long id, @NotNull String address, @NotNull String icon_url, int score) {
        this.id = id;
        this.address = address;
        this.icon_url = icon_url;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

    @NotNull
    public String getIcon_url() {
        return icon_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIcon_url(@NotNull String icon_url) {
        this.icon_url = icon_url;
    }

    public int getScore() {
        return score;
    }

    public void setScore(int score) {
        this.score = score;
    }

}
